server:
  servlet:
    encoding:
      force: 'true'
      enabled: 'true'
      charset: utf-8
cloud:
  aws:
    s3:
      bucket: junior-test-bucket
    credentials:
      accessKey: ${access_key}
      secretKey: ${secret_key}
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  redis:
    host: localhost
    # redistest.tnn4hq.ng.0001.apn2.cache.amazonaws.com:6379
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: 'true'
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
  datasource:
    url: ${DATA_SOURCE}
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: ${JWT_SECRET_KEY}
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace